version: '3.7'
services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
volumes:
  db_data:
